// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMZ5YIxp9im87PvF-MD43AVG4cuf7NmcQ',
    appId: '1:756102838833:web:6de5ff6d55dac42737f310',
    messagingSenderId: '756102838833',
    projectId: 'chatify-782e7',
    authDomain: 'chatify-782e7.firebaseapp.com',
    storageBucket: 'chatify-782e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-V5yJpgbKVAgOH6Gu6WzjVS5oBo0oaFw',
    appId: '1:756102838833:android:80a915a252fd393b37f310',
    messagingSenderId: '756102838833',
    projectId: 'chatify-782e7',
    storageBucket: 'chatify-782e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxWrR7FcPDJWBvh-siNCtYbLlKXv-Smc',
    appId: '1:756102838833:ios:d5fd4300193712ba37f310',
    messagingSenderId: '756102838833',
    projectId: 'chatify-782e7',
    storageBucket: 'chatify-782e7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxWrR7FcPDJWBvh-siNCtYbLlKXv-Smc',
    appId: '1:756102838833:ios:d5fd4300193712ba37f310',
    messagingSenderId: '756102838833',
    projectId: 'chatify-782e7',
    storageBucket: 'chatify-782e7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMZ5YIxp9im87PvF-MD43AVG4cuf7NmcQ',
    appId: '1:756102838833:web:eaee07422defa8f837f310',
    messagingSenderId: '756102838833',
    projectId: 'chatify-782e7',
    authDomain: 'chatify-782e7.firebaseapp.com',
    storageBucket: 'chatify-782e7.firebasestorage.app',
  );
}
